# Taller Integrador — Módulo 1
## Máster en IA & Data Science | DevSeniorCode

**Nombre del estudiante:** Silvia Daniela Merchán Salcedo

**Fecha de entrega:** 27/03/2026

**Repositorio GitHub:** https://github.com/silviadanielam/Taller_Modulo1_IA_DS.git

---

> Este taller evalúa todo lo visto en el Módulo 1:  
> Python · Pandas · Git & GitHub · Documentación

### ¿Cómo entregar?
1. Completa todas las celdas marcadas con 
2. Asegúrate de que el notebook corra sin errores (Kernel → Restart & Run All)
3. Sube el notebook y el CSV a tu repositorio de GitHub
4. Incluye un README.md con tu nombre y una descripción breve del proyecto

---

## Contexto del Dataset

Trabajarás con el dataset **`salud_mundial.csv`**, que contiene indicadores de salud de **159 países**.

| Columna | Descripción |
|---|---|
| `pais` | Nombre del país |
| `region` | Continente o región geográfica |
| `nivel_ingresos` | Nivel económico: Low, Medium, High, Very High |
| `esperanza_vida` | Esperanza de vida al nacer (años) |
| `gasto_salud_usd` | Gasto per cápita en salud (USD/año) |
| `mortalidad_infantil` | Muertes por cada 1,000 nacidos vivos |
| `medicos_por_1000` | Médicos por cada 1,000 habitantes |
| `poblacion_urbana_pct` | % de población que vive en zonas urbanas |
| `obesidad_pct` | % de la población con obesidad |
| `diabetes_pct` | % de la población con diabetes |
| `tabaquismo_pct` | % de fumadores |
| `camas_hospital_por_1000` | Camas hospitalarias por 1,000 hab. |
| `vacunacion_pct` | % de cobertura de vacunación |

---

---
## Parte 1 — Python Fundamental
### (30 puntos)

Antes de usar Pandas, demostraremos que dominas las estructuras básicas de Python.

---

### 1.1 — Listas y operaciones básicas

Tienes la siguiente lista con la esperanza de vida de 10 países (en años).

In [37]:
# Lista dada — NO modificar
esperanzas_de_vida = [72.3, 81.5, 60.1, 78.9, 55.4, 83.2, 67.8, 74.0, 49.3, 79.6]

**Ejercicio 1.1** — Usando Python puro (sin Pandas ni funciones built-in como `sum()` o `max()`):
- Calcula el **promedio** de la lista usando un bucle `for`
- Encuentra el **valor máximo** usando un bucle `for`
- Encuentra el **valor mínimo** usando un bucle `for`

In [38]:
# Tu código aquí

# Promedio
suma = 0

for esperanza_de_vida in esperanzas_de_vida:
    suma = suma + esperanza_de_vida

promedio = suma / len(esperanzas_de_vida) #Len: longitud de la lista, número de datos de la lista.
print ("El promedio de la lista es: ", promedio)

# Máximo

maximo = esperanzas_de_vida[0] #Se asume la primera posición de la lista como el valor máximo, de forma inicial.

for esperanza_de_vida in esperanzas_de_vida:
    if esperanza_de_vida > maximo: #Si el valor de cada posición de la lista es mayor a maximo entonces se le asigna el valor a la variable maximo.
        maximo = esperanza_de_vida 

print("El valor máximo de la lista es: ", maximo)

# Mínimo

minimo = esperanzas_de_vida[0] #Se asume la primera posición de la lista como el valor mínimo, de forma inicial.

for esperanza_de_vida in esperanzas_de_vida:
    if esperanza_de_vida < minimo:
        minimo = esperanza_de_vida

print("El valor mínimo de la lista es: ", minimo)

El promedio de la lista es:  70.21000000000001
El valor máximo de la lista es:  83.2
El valor mínimo de la lista es:  49.3

### 1.2 — Diccionarios

Los diccionarios son fundamentales en Data Science para representar registros.

**Ejercicio 1.2** — Crea un diccionario llamado `pais_info` que represente a Colombia con los siguientes campos:
- `nombre`: "Colombia"
- `region`: "Americas"  
- `esperanza_vida`: 76.5
- `gasto_salud_usd`: 560.3
- `nivel_ingresos`: "High"

Luego:
1. Imprime solo las **claves** del diccionario
2. Imprime solo los **valores**
3. Agrega un nuevo campo: `vacunacion_pct` con valor 82.1
4. Imprime el diccionario completo

In [39]:
# Tu código aquí
pais_info = {
    "nombre" : "Colombia", 
    "region" : "Americas",
    "esperanza_vida" : 76.5,
    "gasto_salud_usd" : 560.3,
    "nivel_ingresos" : "High",
}

#Imprimir las claves del diccionario:
print("1. Imprimiendo solo las claves del diccionario:")
for clave, valor in pais_info.items():
    print(clave)
print("---------------------------------------------------")

#Imprimir los valores del diccionario:
print("2. Imprimiendo solo los valores del diccionario:")
for clave, valor in pais_info.items():
    print(valor)
print("---------------------------------------------------")

#Agrega un nuevo campo: vacunation_pct con valor 82.1
pais_info["vacunation_pct"] = 82.1

#Imprimir el diccionario completo
print("3 y 4. Imprimiendo el diccionario completo:")
print(pais_info)
print("---------------------------------------------------")

print("Imprimiendo diccionario completo de forma ordenada:")
for clave, valor in pais_info.items():
    print(clave, ":" , valor)

1. Imprimiendo solo las claves del diccionario:
nombre
region
esperanza_vida
gasto_salud_usd
nivel_ingresos
---------------------------------------------------
2. Imprimiendo solo los valores del diccionario:
Colombia
Americas
76.5
560.3
High
---------------------------------------------------
3 y 4. Imprimiendo el diccionario completo:
{'nombre': 'Colombia', 'region': 'Americas', 'esperanza_vida': 76.5, 'gasto_salud_usd': 560.3, 'nivel_ingresos': 'High', 'vacunation_pct': 82.1}
---------------------------------------------------
Imprimiendo diccionario completo de forma ordenada:
nombre : Colombia
region : Americas
esperanza_vida : 76.5
gasto_salud_usd : 560.3
nivel_ingresos : High
vacunation_pct : 82.1

### 1.3 — Funciones

Las funciones nos permiten reutilizar lógica.

**Ejercicio 1.3** — Crea una función llamada `clasificar_esperanza_vida` que reciba un número (años) y retorne:
- `"Alta"` si es >= 75
- `"Media"` si es entre 60 y 74.9
- `"Baja"` si es < 60

Prueba la función con al menos 5 valores distintos e imprime los resultados.

In [40]:
# Tu código aquí

def clasificar_esperanza_vida(años): #Se establece la función mediante def, con el parámetro años
    if años >=75:
        return("Alta")
    elif 60 <= años <=74.9:
        return("Media")
    else:
        return("Baja")

print(clasificar_esperanza_vida(25)) #Llamando la función clasificar_esperanza_vida
print(clasificar_esperanza_vida(60))
print(clasificar_esperanza_vida(70))
print(clasificar_esperanza_vida(86))
print(clasificar_esperanza_vida(12))

Baja
Media
Media
Alta
Baja

### 1.4 — Listas + Funciones + Bucles (integrador)

**Ejercicio 1.4** — Usa la función creada en 1.3 y la lista del ejercicio 1.1 para:
1. Crear una **nueva lista** llamada `clasificaciones` que contenga la clasificación de cada esperanza de vida
2. Imprimir cada par: `(valor, clasificación)` usando un bucle `for`

In [41]:
# Tu código aquí

#Lista Punto 1.1:
esperanzas_de_vida = [72.3, 81.5, 60.1, 78.9, 55.4, 83.2, 67.8, 74.0, 49.3, 79.6]

clasificaciones=[] #Nueva lista vacía para guardar clasificaciones.

for esperanza_de_vida in esperanzas_de_vida:
    clasificacion = clasificar_esperanza_vida(esperanza_de_vida)
    clasificaciones.append(clasificacion) #Guardando cada clasificación en la lista clasificaciones
    print(esperanza_de_vida, ":", clasificacion) #Imprimiendo cada para (valor, clasificación)

72.3 : Media
81.5 : Alta
60.1 : Media
78.9 : Alta
55.4 : Baja
83.2 : Alta
67.8 : Media
74.0 : Media
49.3 : Baja
79.6 : Alta

---
## Parte 2 — Análisis con Pandas
### (50 puntos)

---

### 2.1 — Carga y exploración inicial

🔧 **Ejercicio 2.1** — Importa Pandas y carga el archivo `salud_mundial.csv`.  
Luego ejecuta los comandos necesarios para responder:
1. ¿Cuántas filas y columnas tiene el dataset?
2. ¿Qué tipos de datos tiene cada columna?
3. ¿Cuántos valores nulos hay por columna?
4. Muestra las primeras 8 filas

In [42]:
# Tu código aquí
import pandas as pd

# Cargar el dataset
salud = pd.read_csv("salud_mundial.csv")

In [43]:
# Dimensiones
salud.shape

(159, 13)

In [44]:
# Tipos de datos
salud.dtypes #También podría usar salud.info() con el cual sabría el número de filas, columnas, tipos de datos y valores no nulos.

pais                           str
region                         str
nivel_ingresos                 str
esperanza_vida             float64
gasto_salud_usd            float64
mortalidad_infantil        float64
medicos_por_1000           float64
poblacion_urbana_pct       float64
obesidad_pct               float64
diabetes_pct               float64
tabaquismo_pct             float64
camas_hospital_por_1000    float64
vacunacion_pct             float64
dtype: object

In [45]:
# Valores nulos
salud.isnull().sum() #isnull() convierte a True lo que es nulo y False lo que no es nulo, y sum() cuenta los True por columna.

pais                        0
region                      0
nivel_ingresos              0
esperanza_vida              4
gasto_salud_usd             5
mortalidad_infantil        10
medicos_por_1000            9
poblacion_urbana_pct        0
obesidad_pct                3
diabetes_pct                7
tabaquismo_pct              4
camas_hospital_por_1000     7
vacunacion_pct              4
dtype: int64

In [46]:
# Primeras 8 filas
salud.head(8)

,pais,region,nivel_ingresos,esperanza_vida,gasto_salud_usd,mortalidad_infantil,medicos_por_1000,poblacion_urbana_pct,obesidad_pct,diabetes_pct,tabaquismo_pct,camas_hospital_por_1000,vacunacion_pct
0,Afghanistan,Asia,Low,60.9,18.4,NaN,0.19,40.8,15.2,9.2,10.1,1.0,41.1
1,Albania,Europe,Medium,65.1,673.8,28.1,1.18,45.0,27.2,9.7,17.3,1.2,84.5
2,Algeria,Africa,Medium,74.5,525.3,28.2,0.59,47.3,15.2,7.6,20.8,1.3,71.4
3,Angola,Africa,Low,NaN,37.1,54.7,0.79,37.4,13.4,7.8,28.2,1.6,48.7
4,Argentina,Americas,High,79.4,1809.5,7.6,NaN,71.5,18.9,10.1,33.0,3.4,81.7
5,Armenia,Europe,Medium,69.2,797.5,24.2,2.44,67.5,10.2,12.8,32.0,2.3,71.1
6,Australia,Oceania,Very High,NaN,9964.1,NaN,4.42,87.2,20.6,10.3,19.7,7.3,93.8
7,Austria,Europe,Very High,83.7,3685.2,3.9,2.71,91.0,31.0,5.9,18.6,6.0,90.9

### 2.2 — Limpieza de datos

🔧 **Ejercicio 2.2** — El dataset tiene algunos valores nulos (¡datos reales siempre tienen este problema!).  
1. Rellena los valores nulos de columnas **numéricas** con la **media** de cada columna
2. Verifica que ya no queden nulos
3. Explica en una celda de texto: ¿Por qué usamos la media y no simplemente eliminamos esas filas?

In [47]:
# Tu código aquí

#1. Rellenar los valores nulos de columnas numéricas con la media de cada columna
salud = salud.fillna(salud.mean(numeric_only=True)) #Nos permite rellenar los valores nulos de todas las columnas numéricas que los tengan, con la media.
print("Información sin valores nulos:")
print(salud)

Información sin valores nulos:
                    pais    region nivel_ingresos  esperanza_vida  \
0            Afghanistan      Asia            Low       60.900000
1                Albania    Europe         Medium       65.100000
2                Algeria    Africa         Medium       74.500000
3                 Angola    Africa            Low       71.085806
4              Argentina  Americas           High       79.400000
..                   ...       ...            ...             ...
154             Slovenia    Europe      Very High       79.200000
155             Suriname  Americas         Medium       66.700000
156            Swaziland    Africa         Medium       69.300000
157          Timor-Leste      Asia            Low       65.100000
158  Trinidad and Tobago  Americas           High       77.800000

     gasto_salud_usd  mortalidad_infantil  medicos_por_1000  \
0               18.4            28.924832          0.190000
1              673.8            28.100000          1.180000
2              525.3            28.200000          0.590000
3               37.1            54.700000          0.790000
4             1809.5             7.600000          1.978333
..               ...                  ...               ...
154           4043.9             4.900000          5.260000
155            766.7            30.200000          2.420000
156            796.3            34.200000          0.560000
157             75.3            47.200000          0.210000
158           1157.8             5.700000          3.190000

     poblacion_urbana_pct  obesidad_pct  diabetes_pct  tabaquismo_pct  \
0                    40.8          15.2           9.2            10.1
1                    45.0          27.2           9.7            17.3
2                    47.3          15.2           7.6            20.8
3                    37.4          13.4           7.8            28.2
4                    71.5          18.9          10.1            33.0
..                    ...           ...           ...             ...
154                  93.1          23.5           5.2            20.6
155                  60.8          13.1          14.7            32.3
156                  59.3          26.6          14.7            20.5
157                  17.4           8.8           3.8             8.0
158                  65.1          19.8          12.7            16.5

     camas_hospital_por_1000  vacunacion_pct
0                   1.000000            41.1
1                   1.200000            84.5
2                   1.300000            71.4
3                   1.600000            48.7
4                   3.400000            81.7
..                       ...             ...
154                 8.000000            96.5
155                 3.300000            83.1
156                 2.400000            86.5
157                 0.900000            67.8
158                 3.047368            84.4

[159 rows x 13 columns]

In [48]:
#2. Verificando que ya no quedan nulos:
print("Valores nulos de cada columna:")
salud.isnull().sum()

Valores nulos de cada columna:

pais                       0
region                     0
nivel_ingresos             0
esperanza_vida             0
gasto_salud_usd            0
mortalidad_infantil        0
medicos_por_1000           0
poblacion_urbana_pct       0
obesidad_pct               0
diabetes_pct               0
tabaquismo_pct             0
camas_hospital_por_1000    0
vacunacion_pct             0
dtype: int64

**Responde aquí** (doble clic para editar):

*¿Por qué usamos la media para rellenar nulos en vez de eliminar las filas?*

> Tu respuesta: Se utiliza la media para reemplazar los valores nulos porque representa el valor promedio de cada columna, permitiendo completar los datos sin alterar significativamente su distribución. De esta forma se conserva la mayor cantidad de información posible. Si se eliminan las filas se puede perder información que podría ser relevante.

### 2.3 — Estadísticas descriptivas

🔧 **Ejercicio 2.3**
1. Muestra el resumen estadístico completo del dataset
2. ¿Cuál es la esperanza de vida **promedio** mundial?
3. ¿Cuál es el país con **mayor** gasto en salud? ¿Y el de **menor**?
4. ¿Cuál es la **mediana** de la mortalidad infantil?

In [49]:
# Tu código aquí

#1. Resumen estadístico completo del dataset:
salud.describe()

,esperanza_vida,gasto_salud_usd,mortalidad_infantil,medicos_por_1000,poblacion_urbana_pct,obesidad_pct,diabetes_pct,tabaquismo_pct,camas_hospital_por_1000,vacunacion_pct
count,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000
mean,71.085806,2217.050000,28.924832,1.978333,58.635220,19.217308,8.843421,22.918065,3.047368,77.616774
std,8.597795,2910.158218,25.442740,1.479252,21.703028,7.145886,2.851086,7.440349,2.147001,15.473480
min,51.100000,18.400000,2.100000,0.030000,16.200000,5.100000,3.100000,8.000000,0.300000,40.300000
25%,65.100000,138.800000,5.900000,0.670000,42.850000,13.600000,6.850000,17.450000,1.300000,68.400000
50%,73.200000,663.000000,23.700000,1.910000,57.100000,19.217308,8.800000,22.700000,2.200000,80.000000
75%,78.850000,3104.900000,43.300000,2.965000,77.950000,24.800000,10.500000,28.600000,4.300000,89.750000
max,84.000000,10311.800000,95.000000,5.430000,96.800000,34.800000,15.000000,40.000000,8.500000,99.000000

In [50]:
#Esperanza de vida promedio mundial:
media_esperanza_vida = salud["esperanza_vida"].mean()
print(media_esperanza_vida)
print("La esperanza de vida promedio mundial es:", media_esperanza_vida) #También se observa en el resumen estadístico de la columna esperanza_vida, en la fila mean.

71.08580645161291
La esperanza de vida promedio mundial es: 71.08580645161291

In [51]:
#País con mayor gasto en salud:
salud.loc[salud["gasto_salud_usd"].idxmax()] #Muestra fila con el valor máximo de gasto_salud_usd.
# Se puede observar que el valor de este gasto coincide con el valor máximo que arrojó el resumen estadístico.

# De acuerdo a los resultados se puede observar que es un país con nivel de ingresos muy alto, lo cual puede estar...
# relacionado con su alto gasto en salud, lo que puede explicar su alta esperanza de vida (82.2%) y la menor mortalidad infantil...
# de todos los países (2.1%).
#También podemos observar su alto porcentaje de población urbana, casi la máxima de acuerdo al resumen estadístico del dataset, ...
# lo que puede explicar el fácil acceso a la salud.

pais                        Slovakia
region                        Europe
nivel_ingresos             Very High
esperanza_vida                  82.2
gasto_salud_usd              10311.8
mortalidad_infantil              2.1
medicos_por_1000                 4.6
poblacion_urbana_pct            95.7
obesidad_pct                    27.6
diabetes_pct                     8.9
tabaquismo_pct                  13.4
camas_hospital_por_1000     3.047368
vacunacion_pct                  97.7
Name: 153, dtype: object

In [52]:
print("El país con mayor gasto en salud es Slovakia")

El país con mayor gasto en salud es Slovakia

In [53]:
#País con menor gasto en salud:
salud.loc[salud["gasto_salud_usd"].idxmin()] #Muestra fila con el valor mínimo de gasto_salud_usd.
# Se puede observar que el valor de este gasto coincide con el valor mínimo que arrojó el reusmen estadístico.

#De acuerdo a la información obtenida, se puede observar que Afghanistan es un país de ingresos bajos, su esperanza de vida..
# es baja respecto a los demás países y sus médicos por cada 1000 habitantes es demasiado bajo. Lo cual puede explicar por qué..
#es el país con menor gasto en salud.

pais                       Afghanistan
region                            Asia
nivel_ingresos                     Low
esperanza_vida                    60.9
gasto_salud_usd                   18.4
mortalidad_infantil          28.924832
medicos_por_1000                  0.19
poblacion_urbana_pct              40.8
obesidad_pct                      15.2
diabetes_pct                       9.2
tabaquismo_pct                    10.1
camas_hospital_por_1000            1.0
vacunacion_pct                    41.1
Name: 0, dtype: object

In [54]:
print("El país con mayor gasto en salud es Afghanistan")

El país con mayor gasto en salud es Afghanistan

In [55]:
#Mediana de la mortalidad infantil
mediana_mortalidad_infantil = salud["mortalidad_infantil"].median()
print ("La mediana de la mortalidad infantil es: ", mediana_mortalidad_infantil) #El valor coincide con el observado en el Resumen estadístico. Fila (50%).

La mediana de la mortalidad infantil es:  23.7

### 2.4 — Filtrado y selección

🔧 **Ejercicio 2.4**
1. Filtra los países de **América** (`region == "Americas"`) y muestra solo las columnas: `pais`, `esperanza_vida`, `gasto_salud_usd`
2. Filtra los países con esperanza de vida **mayor a 80 años** — ¿cuántos son? ¿De qué regiones son?
3. Filtra los países con **nivel_ingresos == "Low"** y calcula su promedio de `mortalidad_infantil`
4. ¿Cuántos países tienen vacunación por encima del 90%?

In [56]:
# Tu código aquí
#1.
salud.loc[salud["region"] == "Americas", ["pais", "esperanza_vida", "gasto_salud_usd"]]

                    pais  esperanza_vida  gasto_salud_usd
4              Argentina       79.400000          1809.50
11               Bolivia       75.800000           322.40
12                Brazil       74.100000          2913.70
16                Canada       78.900000          4019.60
17                 Chile       79.200000           854.50
19              Colombia       75.200000          2133.70
21            Costa Rica       76.300000          1772.80
23                  Cuba       78.900000          1804.20
26    Dominican Republic       71.085806           591.40
27               Ecuador       69.200000           638.80
29           El Salvador       71.900000           216.20
36             Guatemala       65.000000           442.80
37                 Haiti       51.200000            37.40
38              Honduras       74.200000           523.90
47               Jamaica       74.300000           279.50
59                Mexico       79.800000          2600.50
66             Nicaragua       74.900000           442.30
71                Panama       75.000000          1640.10
72              Paraguay       69.800000          2217.05
73                  Peru       72.700000           240.20
103        United States       81.200000          7230.70
104              Uruguay       78.400000          2744.30
106            Venezuela       73.600000           357.20
139               Guyana       65.700000           663.00
155             Suriname       66.700000           766.70
158  Trinidad and Tobago       77.800000          1157.80

In [57]:
#2.
salud_filtrado = salud.loc[salud["esperanza_vida"] > 80, ["pais", "region"]]
print(salud_filtrado)

                     pais    region
7                 Austria    Europe
10                Belgium    Europe
24         Czech Republic    Europe
25                Denmark    Europe
35                 Greece    Europe
44                Ireland    Europe
45                 Israel      Asia
46                  Italy    Europe
52                 Kuwait      Asia
64            Netherlands    Europe
76               Portugal    Europe
87            South Korea      Asia
88                  Spain    Europe
101  United Arab Emirates      Asia
102        United Kingdom    Europe
103         United States  Americas
114               Iceland    Europe
116            Luxembourg    Europe
129                Brunei      Asia
136               Estonia    Europe
142                Latvia    Europe
148                 Malta    Europe
153              Slovakia    Europe

In [58]:
#Para contar el número de filas filtradas:
len(salud_filtrado)

23

In [59]:
print("El número de países con esperanza de vida mayor a 80 años es 23")

El número de países con esperanza de vida mayor a 80 años es 23

In [60]:
#Para saber de qué regiones son sin escribirlos a mano:
salud_filtrado["region"].unique()

<StringArray>
['Europe', 'Asia', 'Americas']
Length: 3, dtype: str

In [61]:
print("Los países con esperanza de vida mayor a 80 años son: Europa, Asia y América")

Los países con esperanza de vida mayor a 80 años son: Europa, Asia y América

In [62]:
#3. Filtrado de los países con nivel_ingresos = Low:
paises_low = salud.loc[salud["nivel_ingresos"] == "Low"]
print(paises_low)

                 pais    region nivel_ingresos  esperanza_vida  \
0         Afghanistan      Asia            Low       60.900000
3              Angola    Africa            Low       71.085806
9          Bangladesh      Asia            Low       59.700000
14           Cambodia      Asia            Low       60.400000
15           Cameroon    Africa            Low       65.400000
20              Congo    Africa            Low       62.200000
30           Ethiopia    Africa            Low       62.000000
34              Ghana    Africa            Low       64.800000
37              Haiti  Americas            Low       51.200000
51              Kenya    Africa            Low       65.600000
53               Laos      Asia            Low       52.100000
56         Madagascar    Africa            Low       51.100000
58               Mali    Africa            Low       56.000000
61         Mozambique    Africa            Low       51.900000
62            Myanmar      Asia            Low       62.000000
63              Nepal      Asia            Low       64.100000
67              Niger    Africa            Low       56.300000
68            Nigeria    Africa            Low       66.500000
70           Pakistan      Asia            Low       63.800000
79             Rwanda    Africa            Low       66.200000
81            Senegal    Africa            Low       61.600000
83       Sierra Leone    Africa            Low       60.900000
85            Somalia    Africa            Low       60.900000
90              Sudan    Africa            Low       59.000000
93              Syria      Asia            Low       66.500000
94           Tanzania    Africa            Low       62.100000
96               Togo    Africa            Low       65.500000
99             Uganda    Africa            Low       58.500000
108             Yemen      Asia            Low       66.400000
109            Zambia    Africa            Low       64.300000
110          Zimbabwe    Africa            Low       64.000000
115       Ivory Coast    Africa            Low       65.200000
121  Papua New Guinea   Oceania            Low       58.500000
123        Tajikistan      Asia            Low       56.600000
127             Benin    Africa            Low       56.500000
130      Burkina Faso    Africa            Low       60.000000
131           Burundi    Africa            Low       51.600000
134          Djibouti    Africa            Low       61.700000
135           Eritrea    Africa            Low       52.300000
138            Guinea    Africa            Low       51.900000
141        Kyrgyzstan      Asia            Low       63.300000
143           Liberia    Africa            Low       55.500000
146            Malawi    Africa            Low       51.600000
149        Mauritania    Africa            Low       60.700000
152       North Korea      Asia            Low       63.000000
157       Timor-Leste      Asia            Low       65.100000

     gasto_salud_usd  mortalidad_infantil  medicos_por_1000  \
0              18.40            28.924832          0.190000
3              37.10            54.700000          0.790000
9              78.80            81.000000          0.650000
14            148.30            72.500000          0.030000
15            129.20            28.924832          0.350000
20             55.50            50.100000          0.340000
30             73.80            77.700000          0.770000
34             92.50            60.500000          0.360000
37             37.40            50.000000          1.978333
51             44.90            34.100000          0.660000
53            129.50            59.600000          0.540000
56             52.10            71.100000          0.450000
58            104.80            78.800000          0.700000
61             73.00            48.400000          0.550000
62             82.50            84.200000          0.650000
63            139.20            35.700000          0.680000
67             53.20            56.600000          0.280000
68            109.30            55.500000          0.480000
70             37.30            58.400000          0.340000
79             34.30            69.500000          0.630000
81            129.10            50.800000          0.290000
83             39.60            92.800000          0.360000
85             82.20            70.800000          0.250000
90           2217.05            49.500000          0.660000
93             55.20            48.800000          0.180000
94             61.80            58.800000          0.220000
96             38.60            28.924832          0.160000
99            135.80            75.700000          0.260000
108            30.80            95.000000          0.390000
109           138.40            54.100000          0.340000
110           145.50            71.700000          1.978333
115            59.80            79.100000          0.130000
121           100.50            45.700000          0.530000
123           119.30            68.300000          0.410000
127            40.10            71.300000          1.978333
130            62.30            76.200000          0.510000
131           145.00            81.100000          0.740000
134            32.80            72.200000          0.140000
135            45.50            74.200000          0.030000
138            82.40            68.600000          0.430000
141           112.30            40.900000          0.120000
143            71.20            76.800000          0.230000
146            33.00            83.300000          0.080000
149           102.00            67.900000          1.978333
152           149.90            93.300000          0.100000
157            75.30            47.200000          0.210000

     poblacion_urbana_pct  obesidad_pct  diabetes_pct  tabaquismo_pct  \
0                    40.8     15.200000      9.200000       10.100000
3                    37.4     13.400000      7.800000       28.200000
9                    21.7      6.500000      6.000000       18.200000
14                   43.6      9.500000      7.600000       30.500000
15                   24.7      5.100000      8.400000       23.300000
20                   29.1     19.217308      3.900000       18.100000
30                   24.5     17.100000      6.800000       19.600000
34                   21.5      5.800000      9.600000       19.500000
37                   34.9      9.300000      3.900000       24.500000
51                   46.8      9.500000      5.900000       11.400000
53                   37.5     14.000000      3.100000       26.900000
56                   26.4     19.900000      6.700000       18.900000
58                   40.2     19.500000      7.200000       16.400000
61                   32.0     15.000000      8.843421       17.500000
62                   17.5     17.900000      8.843421        8.400000
63                   23.5     13.800000      6.700000       17.500000
67                   35.9     16.800000      7.500000        9.600000
68                   47.8      9.600000      5.600000       27.000000
70                   38.7      8.600000      6.100000       14.800000
79                   16.2      6.000000      8.400000       16.800000
81                   17.3     13.100000      9.200000       28.400000
83                   46.9      5.800000      3.900000       11.700000
85                   48.5     12.200000      8.600000       24.400000
90                   27.9     15.100000      9.900000       22.000000
93                   39.7      9.800000      5.400000       30.400000
94                   31.8      8.000000      6.800000       30.400000
96                   47.2     20.000000      5.800000       19.900000
99                   19.1     18.700000      5.100000       22.800000
108                  23.5     14.100000      4.400000       30.000000
109                  34.7      8.300000      4.000000       14.300000
110                  20.9     16.900000      4.200000       25.300000
115                  49.6     15.900000      6.500000       22.918065
121                  40.0     16.800000      3.500000       31.800000
123                  27.1      5.400000      3.700000       18.000000
127                  37.6     20.000000      6.900000       19.800000
130                  20.8      7.100000      4.400000       13.000000
131                  49.7     18.000000      3.900000       28.800000
134                  47.6      9.100000      7.600000       14.000000
135                  39.3     17.300000      9.900000       18.100000
138                  49.2     19.800000      8.843421       11.200000
141                  42.3      9.000000      9.200000       26.500000
143                  17.7     10.600000      6.500000       29.600000
146                  34.9     11.500000      9.700000       13.700000
149                  43.4      5.300000      3.500000       29.700000
152                  38.0      9.000000      8.700000       30.000000
157                  17.4      8.800000      3.800000        8.000000

     camas_hospital_por_1000  vacunacion_pct
0                   1.000000       41.100000
3                   1.600000       48.700000
9                   1.000000       67.700000
14                  0.400000       44.400000
15                  0.700000       68.200000
20                  1.900000       65.700000
30                  1.000000       67.800000
34                  1.700000       55.200000
37                  1.500000       75.800000
51                  1.900000       51.600000
53                  0.600000       44.800000
56                  1.300000       43.800000
58                  1.200000       48.100000
61                  1.300000       40.300000
62                  1.900000       72.800000
63                  0.800000       52.900000
67                  0.400000       65.800000
68                  1.700000       65.500000
70                  1.500000       57.100000
79                  0.900000       61.600000
81                  3.047368       75.200000
83                  0.500000       52.300000
85                  0.700000       42.800000
90                  1.600000       67.600000
93                  1.600000       50.400000
94                  1.500000       45.200000
96                  1.900000       76.600000
99                  0.600000       45.100000
108                 1.200000       69.500000
109                 1.900000       62.000000
110                 1.100000       74.800000
115                 0.300000       56.600000
121                 1.100000       55.200000
123                 1.900000       44.400000
127                 0.500000       52.000000
130                 0.300000       53.300000
131                 0.600000       67.000000
134                 3.047368       74.300000
135                 0.400000       42.700000
138                 1.700000       77.616774
141                 0.300000       70.700000
143                 0.500000       77.616774
146                 0.700000       52.000000
149                 1.000000       44.900000
152                 0.300000       77.900000
157                 0.900000       67.800000

In [63]:
#Promedio de mortalidad infantil de los países con nivel de ingresos Low:
media_paises_low = paises_low["mortalidad_infantil"].mean()
print(media_paises_low)
print("El promedio de mortalidad infantil de los países con nivel de ingresos low es:", media_paises_low)

63.02770644878905
El promedio de mortalidad infantil de los países con nivel de ingresos low es: 63.02770644878905

In [64]:
#4. ¿Cuántos países tienen vacunación por encima del 90%?
vacunacion_superior = salud.loc[salud["vacunacion_pct"] > 90, ["pais"]]
print(vacunacion_superior)

#Para contar el número de filas filtradas:
len(vacunacion_superior)
#Imprimiendo:
print("El número de países con vacunación superior al 90% es: ", len(vacunacion_superior))

                     pais
6               Australia
7                 Austria
10                Belgium
17                  Chile
23                   Cuba
32                 France
35                 Greece
44                Ireland
46                  Italy
48                  Japan
52                 Kuwait
57               Malaysia
64            Netherlands
69                 Norway
71                 Panama
75                 Poland
76               Portugal
80           Saudi Arabia
82                 Serbia
84              Singapore
87            South Korea
88                  Spain
92            Switzerland
98                 Turkey
101  United Arab Emirates
102        United Kingdom
103         United States
104               Uruguay
114               Iceland
116            Luxembourg
120                  Oman
122                 Qatar
129                Brunei
136               Estonia
142                Latvia
144             Lithuania
148                 Malta
153              Slovakia
154              Slovenia
El número de países con vacunación superior al 90% es:  39

### 2.5 — Agrupaciones

🔧 **Ejercicio 2.5** — Usa `groupby()` para:
1. Calcular la **esperanza de vida promedio** por `region`
2. Calcular el **gasto en salud promedio** por `nivel_ingresos`
3. Calcular el **número de países** por región
4. ¿Qué región tiene la mayor esperanza de vida promedio? ¿Y la menor?

In [65]:
# Tu código aquí
#1. Esperanza de vida promedio por region

salud.groupby("region")["esperanza_vida"].mean()

region
Africa      63.513623
Americas    73.472531
Asia        70.704762
Europe      77.651950
Oceania     68.746452
Name: esperanza_vida, dtype: float64

In [66]:
#2. Gasto en salud promedio por nivel_ingresos

salud.groupby("nivel_ingresos")["gasto_salud_usd"].mean()

#De acuerdo a los datos obtenidos, podemos observar que el nivel de ingresos es directamente proporcional al gasto en salud promedio
#A mayor nivel de ingresos mayor gasto en salud.

nivel_ingresos
High         2003.016000
Low           126.881522
Medium        593.864894
Very High    6553.350000
Name: gasto_salud_usd, dtype: float64

In [67]:
#3. Número de países por región
salud.groupby("region")["pais"].count()

region
Africa      43
Americas    26
Asia        42
Europe      44
Oceania      4
Name: pais, dtype: int64

In [68]:
#4. ¿Qué región tiene la mayor esperanza de vida promedio? ¿Y la menor?
promedio = salud.groupby("region")["esperanza_vida"].mean() #Esperanza de vida promedio por región
print(promedio)

#Mayor esperanza de vida promedio:
promedio.idxmax()
print("La región con mayor esperanza de vida promedio es ", promedio.idxmax())

#Menor esperanza de vida promedio:
promedio.idxmin()
print("La región con menor esperanza de vida promedio es ", promedio.idxmin())

region
Africa      63.513623
Americas    73.472531
Asia        70.704762
Europe      77.651950
Oceania     68.746452
Name: esperanza_vida, dtype: float64
La región con mayor esperanza de vida promedio es  Europe
La región con menor esperanza de vida promedio es  Africa

### 2.6 — Nueva columna calculada

🔧 **Ejercicio 2.6**
1. Crea una nueva columna llamada `categoria_vida` aplicando la función `clasificar_esperanza_vida` que creaste en la Parte 1 a la columna `esperanza_vida`
2. ¿Cuántos países caen en cada categoría? (usa `value_counts()`)
3. ¿Qué porcentaje del total representa cada categoría?

In [69]:
# Tu código aquí
#1. Nueva columna llamada categoria_vida
salud["categoria_vida"] = salud["esperanza_vida"].apply(clasificar_esperanza_vida) #Usando método apply
print(salud.head())

          pais    region nivel_ingresos  esperanza_vida  gasto_salud_usd  \
0  Afghanistan      Asia            Low       60.900000             18.4
1      Albania    Europe         Medium       65.100000            673.8
2      Algeria    Africa         Medium       74.500000            525.3
3       Angola    Africa            Low       71.085806             37.1
4    Argentina  Americas           High       79.400000           1809.5

   mortalidad_infantil  medicos_por_1000  poblacion_urbana_pct  obesidad_pct  \
0            28.924832          0.190000                  40.8          15.2
1            28.100000          1.180000                  45.0          27.2
2            28.200000          0.590000                  47.3          15.2
3            54.700000          0.790000                  37.4          13.4
4             7.600000          1.978333                  71.5          18.9

   diabetes_pct  tabaquismo_pct  camas_hospital_por_1000  vacunacion_pct  \
0           9.2            10.1                      1.0            41.1
1           9.7            17.3                      1.2            84.5
2           7.6            20.8                      1.3            71.4
3           7.8            28.2                      1.6            48.7
4          10.1            33.0                      3.4            81.7

  categoria_vida
0          Media
1          Media
2          Media
3          Media
4           Alta

In [70]:
#2. Cuántos países caen en cada categoría?
numero_paises = salud["categoria_vida"].value_counts()
print(numero_paises)

categoria_vida
Media    79
Alta     63
Baja     17
Name: count, dtype: int64

In [71]:
#3. ¿Qué porcentaje del total representa cada categoría?
porcentaje = salud["categoria_vida"].value_counts(normalize=True).mul(100).round(2) #Se obtiene la proporción de cada valor respecto al total y se multiplica por 100, además se redondearon
#los decimales a 2.
print(porcentaje)

categoria_vida
Media    49.69
Alta     39.62
Baja     10.69
Name: proportion, dtype: float64

### 2.7 — Análisis libre (desafío)

**Ejercicio 2.7 (Opcional — puntos extra)** — Formula **una pregunta propia** sobre el dataset y respóndela con código.  

Ejemplos de preguntas que podrías hacer:
- ¿Existe relación entre el gasto en salud y la esperanza de vida?
- ¿Los países con más médicos tienen menor mortalidad infantil?
- ¿Qué región tiene mayor tasa de obesidad?

**Escribe tu pregunta:**

Pregunta formulada: ¿Cómo se comporta la tasa de obesidad respecto al nivel de ingresos de los países?

In [72]:
# Tu código aquí
salud.groupby("nivel_ingresos")["obesidad_pct"].mean().sort_values() #Mediante mean() obtenemos el promedio de obesidad por cada nivel de ingresos,
#sort_values ordena de menor a mayor.

#Análisis:
#De acuerdo a los resultados, se puede observar que los países con nivel de ingresos muy altos tienden a tener mayores niveles de obsedidad,
#lo que puede estar relacionado al fácil acceso a los alimentos, posible sedentarismo o malos hábitos alimenticios.
#El porcentaje de obesidad en los países con menores ingresos es menor posiblemente debido al difícil acceso a los alimentos.

nivel_ingresos
Low          12.550376
Medium       17.719885
High         23.196000
Very High    25.987805
Name: obesidad_pct, dtype: float64

---
## Parte 3 — Git & GitHub
### (20 puntos)

Esta parte se evalúa por el **estado real de tu repositorio** en GitHub.  
Documenta los comandos que usaste respondiendo las preguntas en las celdas de texto.

---

### 3.1 — Configuración del repositorio

**Responde** (doble clic para editar):

**¿Qué comandos usaste para crear e inicializar tu repositorio local?**
```bash
# Tu respuesta:

Para crear una carpeta para el proyecto:
mkdir Taller_Modulo1 cd Taller_Modulo1

Para inicializar mi repositorio local:
git init
```

**¿Cómo conectaste tu repositorio local con GitHub?**
```bash
# Tu respuesta:
git remote add origin https://github.com/silviadanielam/Taller_Modulo1_IA_DS.git
```

### 3.2 — Flujo de trabajo

**Responde:**

**¿Qué comando usaste para añadir los archivos al staging area?**
```bash
# Tu respuesta:
#Primero usé git status parfa ver el estado en el que iba en git.
git add . #Para agregar todos los archivos.

```

**¿Qué mensaje de commit escribiste? ¿Por qué elegiste ese mensaje?**
```bash
# Tu respuesta:

git commit -m "Agregando archivos taller_modulo1.ipynb, salud_mundial.csv y README"


```

**¿Cómo subiste los cambios a GitHub?**
```bash
# Tu respuesta:
git push -u origin main

```

### 3.3 — Buenas prácticas

**Responde:**

**¿Qué archivos debería incluir un `.gitignore` en un proyecto de Data Science? Menciona al menos 3 y explica por qué.**

> Tu respuesta:
1. Archivos de datos grandes (CSV, Excel, entre otros), ya que pueden ser muy pesados y pueden ser datos sensibles o privados.
2. Archivos de entorno virtual como .env, ya que puede tener contrseñas o claves API.
3. Archivos temporales o de Jupyter, ya que son archivos temporales que se crean automáticamente al trabajar con notebooks y no aportan valor al proyecto.

**¿Cuál es la diferencia entre `git add .` y `git add nombre_archivo`?**

> Tu respuesta: git add . permite subir todos los archivos de una carpeta al mismo tiempo, mientras que git add nombre_archivo sube un archivo en específico solamente.

---
## Parte 4 — Documentación (README)
### (Evaluada en GitHub)

Tu repositorio debe tener un archivo `README.md` que incluya:

- [ ] Título del proyecto
- [ ] Tu nombre
- [ ] Descripción del dataset (qué contiene, cuántos países, fuente)
- [ ] Cómo ejecutar el notebook (instrucciones paso a paso)
- [ ] Al menos 3 hallazgos o conclusiones del análisis
- [ ] Tecnologías usadas (Python, Pandas, Jupyter, Git)

---

### Checklist de entrega

Antes de hacer tu commit final, verifica:

- [ ] El notebook corre completo sin errores (Kernel → Restart & Run All)
- [ ] Todas las celdas están completadas
- [ ] Las celdas de texto tienen tus respuestas
- [ ] El archivo `salud_mundial.csv` está en el repositorio
- [ ] El `README.md` está completo
- [ ] El link al repositorio está en la celda de portada

---

## Criterios de evaluación

| Sección | Puntos |
|---|---|
| Parte 1 — Python | 30 |
| Parte 2 — Pandas | 50 |
| Parte 3 — Git | 20 |
| README en GitHub | 10 |
| Ejercicio libre 2.7 | +10 |
| **Total** | **110** |